name: Daily LinkedIn AI Post

on:
  schedule:
    - cron: '0 7 * * *' # Runs every day at 7:00 UTC
  workflow_dispatch:

jobs:
  post-linkedin:
    runs-on: ubuntu-latest
    env:
      LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
      LINKEDIN_PROFILE_ID: ${{ secrets.LINKEDIN_PROFILE_ID }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Social Agent
        run: |
          python main.py
